package cli

// scanFacts is an original deck of compact trivia for interactive scans. Keep
// facts short enough to remain readable after terminal-width truncation.
var scanFacts = []string{
	"Venus has a day longer than its year.",
	"Mercury completes a year in 88 Earth days.",
	"Jupiter spins once in about ten hours.",
	"Uranus rotates almost completely on its side.",
	"Sunlight reaches Earth in about eight minutes.",
	"The Moon drifts away from Earth each year.",
	"Mars has blue sunsets.",
	"Comet tails point away from the Sun.",
	"The Moon keeps the same face toward Earth.",
	"The ISS circles Earth roughly every 90 minutes.",
	"Saturn is less dense than water on average.",
	"The Sun holds most of the solar system's mass.",
	"Polaris is not the brightest star in the sky.",
	"Earth is closest to the Sun during January.",
	"Earth's tilt causes seasons, not its solar distance.",
	"Auroras begin with charged particles from the Sun.",
	"The Milky Way is a barred spiral galaxy.",
	"Olympus Mons is the solar system's tallest volcano.",
	"The Moon has no weather like Earth's wind or rain.",
	"Sound cannot travel through a perfect vacuum.",
	"A solar day on Mercury lasts 176 Earth days.",
	"Neptune has some of the solar system's fastest winds.",
	"Jupiter's Great Red Spot is a giant storm.",
	"The Sun is a star, not a planet.",
	"A lunar eclipse can turn the Moon copper-red.",
	"Octopuses have three hearts.",
	"Wombats make cube-shaped droppings.",
	"Butterflies taste with sensors on their feet.",
	"Hummingbirds can fly backward.",
	"Owls have tube-shaped eyes.",
	"Goats have rectangular pupils.",
	"Reindeer eyes change color with the seasons.",
	"Sharks existed before trees.",
	"Greenland sharks can live for centuries.",
	"Mantis shrimp strikes can create tiny shock waves.",
	"Axolotls can regrow entire limbs.",
	"Tardigrades can survive vacuum while dormant.",
	"Sloth fur can host entire algae communities.",
	"A group of flamingos is called a flamboyance.",
	"Ravens can imitate human speech.",
	"Cats lack a working sweet-taste receptor.",
	"Elephants cannot jump.",
	"Koala fingerprints look remarkably human.",
	"Male seahorses carry developing young.",
	"Clownfish can change sex.",
	"Some parrotfish sleep inside mucus cocoons.",
	"Ants breathe through openings called spiracles.",
	"Honeybees dance to share directions.",
	"Dragonflies lived before dinosaurs.",
	"Horseshoe crabs predate dinosaurs.",
	"Squid have three hearts.",
	"Platypuses glow blue-green under ultraviolet light.",
	"Male platypuses have venomous ankle spurs.",
	"Frogs absorb water through their skin.",
	"Penguins have knees hidden beneath their feathers.",
	"Polar bears have black skin beneath clear fur.",
	"Cuttlefish have W-shaped pupils.",
	"Snails scrape food with thousands of tiny teeth.",
	"Crickets hear through organs on their front legs.",
	"Lyrebirds can copy sounds like camera shutters.",
	"Bats are the only mammals capable of sustained flight.",
	"Flying squirrels glide rather than truly fly.",
	"Hippo skin makes reddish natural sunscreen pigments.",
	"Camels have three eyelids on each eye.",
	"Rats make ultrasonic chirps when tickled.",
	"Rabbits can see nearly all the way around themselves.",
	"Chameleons can move their eyes independently.",
	"Gecko toes use millions of microscopic hairs.",
	"Sea stars have no centralized brain.",
	"Jellyfish have neither brains nor hearts.",
	"Sponges are animals.",
	"Corals are colonies of tiny animals.",
	"Puffin bills fluoresce under ultraviolet light.",
	"Sea otters sometimes hold paws while resting.",
	"Dolphins use individual signature whistles.",
	"Bananas are berries in botanical terms.",
	"Strawberries are not botanical berries.",
	"Peanuts are legumes, not nuts.",
	"Cashews grow attached to cashew apples.",
	"Pineapples are clusters of fused fruits.",
	"A sunflower head contains many tiny flowers.",
	"Bamboo is a grass.",
	"Avocados are botanical berries.",
	"Vanilla comes from an orchid.",
	"Saffron is made from crocus flower stigmas.",
	"Apples float because their tissues contain air.",
	"Broccoli, kale, and cabbage are the same species.",
	"Fig flowers bloom inside the structure we eat.",
	"Fungi are evolutionarily closer to animals than plants.",
	"A giant honey fungus is among Earth's largest organisms.",
	"Bristlecone pines can live for thousands of years.",
	"Ginkgo trees predate flowering plants.",
	"Mosses use rhizoids instead of true roots.",
	"Ferns reproduce with spores, not seeds.",
	"Some bamboo can grow nearly a meter in a day.",
	"Potatoes and tomatoes belong to the nightshade family.",
	"Coffee beans are seeds inside fruit.",
	"Cacao pods grow directly from trunks and branches.",
	"A coconut is a drupe, not a true nut.",
	"The smell after rain is called petrichor.",
	"Antarctica is Earth's largest desert.",
	"Water expands when it freezes.",
	"The Pacific Ocean is wider than the Moon.",
	"The ocean covers about 71 percent of Earth.",
	"Continents move about as fast as fingernails grow.",
	"Lightning heats nearby air hotter than the Sun's surface.",
	"Mauna Kea is taller than Everest from base to peak.",
	"Earth's inner core is mostly iron and nickel.",
	"The Sahara has repeatedly shifted between green and dry.",
	"Clouds can weigh hundreds of tons.",
	"Most volcanic activity happens beneath the ocean.",
	"Earth has a mobile system of tectonic plates.",
	"Fresh snow can contain mostly air.",
	"Glaciers hold most of Earth's fresh water.",
	"Lake Baikal is the world's deepest freshwater lake.",
	"The Dead Sea is a lake, not a sea.",
	"A bolt of lightning can stretch for hundreds of miles.",
	"Sand dunes can make booming sounds.",
	"Obsidian is volcanic glass.",
	"Pumice can float on water.",
	"The stapes is the smallest bone in the human body.",
	"Skin is the human body's largest organ.",
	"The cornea has no blood vessels.",
	"Babies are born with more bones than adults.",
	"The left lung is smaller than the right lung.",
	"The liver can regrow lost tissue.",
	"Fingerprints form before birth.",
	"Red blood cells have no nuclei when mature.",
	"The brain uses roughly one-fifth of the body's energy.",
	"You are usually slightly taller in the morning.",
	"Teeth are not bones.",
	"Goosebumps are produced by tiny skin muscles.",
	"Taste-bud cells are replaced throughout life.",
	"The human nose can detect an enormous range of odors.",
	"A blink usually lasts less than half a second.",
	"Zero has no standard Roman numeral.",
	"A googol is one followed by one hundred zeros.",
	"A Möbius strip has only one side.",
	"The number one is neither prime nor composite.",
	"Pi is irrational.",
	"With 23 people, a shared birthday is more likely than not.",
	"A shuffled 52-card deck has astronomically many orders.",
	"Hexagons can tile a flat surface without gaps.",
	"Oxford University predates the Aztec Empire.",
	"Nintendo was founded in 1889.",
	"The fax machine was patented before the telephone.",
	"The can opener was invented decades after canned food.",
	"Bubble wrap was first marketed as textured wallpaper.",
	"Velcro was inspired by burrs clinging to fabric.",
	"Bookkeeper has three consecutive double letters.",
}
